server {
    listen 80;
    server_name www.hinzke.rocks;
    return 301 https://hinzke.rocks$request_uri;
}

server {
    listen 80;
    server_name hinzke.rocks;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    error_page 404 /404.html;
}
